softmax with one sample set, (vector)

In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([-0.53526021, -0.20122984,  1.18212202,  0.00468348,  0.33323175])

In [4]:
expa = np.exp(a)

In [5]:
expa

array([0.58551692, 0.81772446, 3.26128739, 1.00469447, 1.39547066])

In [6]:
answer = expa/ expa.sum()

In [7]:
answer

array([0.0828793 , 0.11574804, 0.4616318 , 0.14221345, 0.19752741])

In [8]:
answer.sum()

1.0

softmax with multiple sample set (matrix)

In [9]:
A = np.random.randn(100, 5)

In [10]:
expA = np.exp(A)

In [11]:
expA

array([[ 0.25436552,  2.10636856,  0.67209799,  0.58202029,  1.23014708],
       [ 1.60340744,  0.99202817,  0.5707954 ,  0.90488886,  2.09854121],
       [ 0.89340545,  1.02692363,  0.32638877,  0.05736949,  1.2052193 ],
       [ 4.5968912 ,  2.72247355,  0.36155958,  0.47330306,  1.3207031 ],
       [ 0.63732086,  1.25747441,  2.61970027,  0.38337582,  1.81657257],
       [ 1.12859801,  0.5869567 ,  0.34529385,  2.5502792 ,  0.50448645],
       [ 5.77777091,  1.35754666,  0.16707433,  4.00694778,  0.12535616],
       [ 6.94983573,  4.96989391,  1.18628786,  0.84174774,  6.99078022],
       [ 2.61823792,  0.67154161,  3.80770946,  3.21697164,  0.21321205],
       [ 0.23268699,  1.50491951,  2.14516517,  0.78460275,  3.02098412],
       [ 0.72270313,  0.5263139 ,  0.87509821,  2.2701935 ,  0.40963401],
       [ 0.5081099 ,  2.01574644,  0.16369186,  2.43161985,  4.15520148],
       [ 0.35643344,  1.43589289,  1.50306693,  0.69161679,  1.99961792],
       [ 2.28005457,  0.93612426,  0.3

In [12]:
answer = expA / expA.sum(axis=1, keepdims=True)

In [14]:
answer.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
answer.shape

(100, 5)