## Section 2: Basics

In [1]:
import numpy as np

In [2]:
N = 100

In [3]:
D = 2

In [5]:
X = np.random.randn(N,D)


In [11]:
ones = np.array([[1]]*N)

In [12]:
Xb = np.concatenate((ones, X), axis=1)

In [14]:
w = np.random.randn(D + 1)

In [15]:
w

array([ 0.49446374, -1.43270576,  0.5373705 ])

In [21]:
z = Xb.dot(w)
z

array([ 1.55558988, -0.33056915, -0.72521119,  0.26754731, -1.89114056,
        0.93694646,  1.61598278, -0.79747539,  2.39892003, -1.14357987,
        0.72139925, -1.09517145,  3.24059503, -0.62341677,  0.88600763,
        2.21526407,  1.36290344,  0.95752747,  0.81281984,  0.61366762,
        0.61426497,  0.81629675,  0.14595327, -0.14180311, -0.95240766,
        0.48042702, -0.6189702 ,  0.49026555,  1.14597337,  0.46282293,
        1.41980487,  0.3285528 , -0.98906228, -1.166678  ,  1.40040753,
       -1.78681179, -2.58172694, -0.74247665,  0.39589664,  0.64889515,
        0.841493  , -2.01101443, -1.86134661, -0.92632649,  0.16398019,
        1.90417876,  2.29140088,  3.27604921,  1.70490039, -0.73961218,
        1.96265857, -0.55821627,  2.47597581,  1.06010272,  2.70902035,
       -1.4458715 ,  1.75321006, -0.84396986, -1.27731761,  1.69124033,
        0.61951481, -0.52221309,  0.14772535, -1.56959215,  3.84009732,
       -0.13827181, -0.72959988,  0.27590258, -0.44164731,  4.38

In [19]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

In [20]:
sigmoid(z)

array([0.82571962, 0.41810215, 0.32624648, 0.56649068, 0.13111448,
       0.71848244, 0.83424036, 0.31056582, 0.91674491, 0.2416637 ,
       0.67291507, 0.25064571, 0.96233368, 0.34900476, 0.7080656 ,
       0.90161188, 0.79623118, 0.72262649, 0.69271007, 0.64877698,
       0.64891308, 0.69344968, 0.53642368, 0.46460851, 0.27840088,
       0.6178487 , 0.3500157 , 0.62016899, 0.75877467, 0.61368364,
       0.80530782, 0.58140721, 0.27109733, 0.23745598, 0.80224855,
       0.14346405, 0.07032374, 0.32246281, 0.59770139, 0.65676144,
       0.69877957, 0.11805132, 0.13454617, 0.28367058, 0.54090343,
       0.87036375, 0.90816236, 0.96359796, 0.84617367, 0.32308896,
       0.87682038, 0.36396028, 0.92244038, 0.74271018, 0.93755682,
       0.19063776, 0.85235723, 0.30069935, 0.21800717, 0.84438721,
       0.65010819, 0.37233489, 0.53686432, 0.17227454, 0.97896066,
       0.46548702, 0.32528254, 0.5685414 , 0.39134852, 0.9876615 ,
       0.38467346, 0.88752665, 0.95282245, 0.93355768, 0.88844