# Numpy Prerequisite

### dot product

In [1]:
import numpy as np

In [2]:
a = np.array([1,2])
b = np.array([2,1])

method 1:

In [3]:
np.sum(a * b)

4

or

In [4]:
(a*b).sum()

4

method 2:

In [5]:
np.dot(a, b)

4

In [6]:
a.dot(b)

4

### get the magnitude (norm)

In [8]:
norm = np.linalg.norm(a)
norm

2.23606797749979

with the equation of dot product

In [10]:
cos_angle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b) )
cos_angle

0.7999999999999998

In [12]:
angle = np.arccos(cos_angle)
angle

0.6435011087932847

### Matrix and Vector

In [13]:
M = np.array( [[1,2], [3,4] ])

In [14]:
L = [[1,2], [3,4]]

In [15]:
L[0][0]

1

In [16]:
M[0][0]

1

In [17]:
M[0,0]

1

In [18]:
M2 = np.matrix( [[1,2], [3,4] ])

In [19]:
M2

matrix([[1, 2],
        [3, 4]])

In [21]:
A = np.array(M2)
A

array([[1, 2],
       [3, 4]])

In [22]:
A.T

array([[1, 3],
       [2, 4]])

### Generating Matrix to Work With

In [23]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [24]:
z = np.zeros((10,10))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
o = np.ones((10,10))
o

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [27]:
R = np.random.random((10, 10))
R

array([[0.71969695, 0.80882614, 0.71025984, 0.22474506, 0.92161465,
        0.82651664, 0.24345664, 0.23721699, 0.99007768, 0.1174372 ],
       [0.51587574, 0.46188056, 0.95452475, 0.70997165, 0.05504152,
        0.67602146, 0.99526056, 0.22848687, 0.07889571, 0.62999153],
       [0.99697825, 0.69455099, 0.68444817, 0.07703765, 0.36065678,
        0.29398529, 0.7741785 , 0.41645612, 0.06176269, 0.76896925],
       [0.04489332, 0.05371527, 0.4692093 , 0.8458374 , 0.8719796 ,
        0.78285994, 0.35340751, 0.03720139, 0.61551677, 0.21816002],
       [0.56118202, 0.11944033, 0.5004039 , 0.88796386, 0.69342508,
        0.54451246, 0.26046183, 0.45609792, 0.11953972, 0.14444584],
       [0.23570848, 0.44073764, 0.07518254, 0.17498903, 0.15623875,
        0.56841661, 0.58880884, 0.08661115, 0.70829236, 0.14227426],
       [0.81103728, 0.05721257, 0.44431801, 0.90186476, 0.55491129,
        0.11666939, 0.48259139, 0.01126355, 0.09709319, 0.87162802],
       [0.68688756, 0.3128831 , 0.0719936

gaussian distribution

In [29]:
G = np.random.randn(10,10)
G

array([[ 0.69378852, -0.50002181, -0.30192674,  1.37061493,  0.10317433,
        -0.73319191,  1.5648944 ,  0.23034759, -1.62266607, -0.01007993],
       [-0.55746907, -0.58486518, -0.59526392, -1.95126627, -1.36109015,
         2.39480517,  0.11556491, -0.86621943,  0.19861099, -1.70731645],
       [ 1.11159568,  1.10046423, -0.28614286, -0.63405843, -1.92706339,
        -1.28880368,  0.97601385,  0.29490806, -0.32573186,  0.11642323],
       [-2.57093756,  0.27607638,  1.24739476,  0.43292566,  0.66817204,
        -0.94089156,  0.46920729, -0.83167636,  1.06427151,  1.02264862],
       [-0.63999817, -0.43641509,  0.10018575,  0.55395932,  0.45624546,
         0.62717795, -1.8134937 , -0.0473118 , -0.30779808,  0.70345504],
       [ 0.4640783 ,  0.86034415, -0.48623586, -1.06616022,  0.29611968,
         1.33645486,  1.61126905, -0.2130055 ,  0.70744197, -0.95572759],
       [ 2.3962623 , -1.59087053, -0.70728893, -0.81974891,  0.22724652,
         1.06228239,  0.23527015, -0.11184007

In [30]:
G.mean()

-0.12889447671773244

In [31]:
G.var()

1.0671487591272426

### Matrix Products

In [40]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [35]:
Ainv = np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [36]:
Ainv.dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [37]:
A.dot(Ainv)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [38]:
np.linalg.det(A)

-2.0000000000000004

In [39]:
np.diag(A)

array([1, 4])

In [41]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [42]:
a = np.array([1,2])
b = np.array([3,4])

In [43]:
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [44]:
np.inner(a,b)

11

In [45]:
a.dot(b)

11

trace

In [46]:
np.diag(A).sum()

5

In [47]:
np.trace(A)

5

Eigenvalue & Eigenvectors

In [50]:
X = np.random.rand(100,3)


In [53]:
cov = np.cov(X)
cov.shape

(100, 100)

In [54]:
cov = np.cov(X.T)
cov.shape

(3, 3)